# Generated by Django 4.2.1 on 2024-09-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pompa',
            name='data_installazione',
        ),
        migrations.RemoveField(
            model_name='pompa',
            name='stato',
        ),
        migrations.RemoveField(
            model_name='stazione',
            name='ubicazione',
        ),
        migrations.AddField(
            model_name='pompa',
            name='girante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pompa',
            name='kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pompa',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pompa',
            name='posizione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pompa',
            name='prevalenza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stazione',
            name='comune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
