# Generated by Django 4.2.1 on 2024-09-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_remove_pompa_data_installazione_remove_pompa_stato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stazione',
            name='comune',
            field=models.CharField(default='Comune Predefinito', max_length=100),
        ),
    ]
